### ISSUE TITLE
OpenGL shader compilation error on OS X

### ISSUE THREAD

**Issue by shmup** [rsaarelm/phage#1]
Perhaps I'm making a mistake. I haven't looked into this, just instantly opened an issue because maybe you'll have a clue before I do. 

Building on OS X 10.10.3

```
jared@firefly phage (master) $ cargo run --verbose
       Fresh khronos_api v0.0.5
       Fresh rustc-serialize v0.3.14
       Fresh gcc v0.3.5
       Fresh lazy_static v0.1.10
       Fresh vec_map v0.0.1
       Fresh byteorder v0.3.9
       Fresh libc v0.1.7
       Fresh bitflags v0.1.1
       Fresh shared_library v0.1.0
       Fresh glutin_core_foundation v0.1.2
       Fresh malloc_buf v0.0.5
       Fresh gl_common v0.0.4
       Fresh log v0.3.1
       Fresh rand v0.3.8
       Fresh xml-rs v0.1.25
       Fresh glutin_core_graphics v0.1.4
       Fresh objc v0.1.5
       Fresh num v0.1.24
       Fresh gl_generator v0.0.25
       Fresh time v0.1.25
       Fresh glutin_cocoa v0.1.5
       Fresh cgmath v0.1.5
       Fresh nalgebra v0.2.14
       Fresh enum_primitive v0.0.1
       Fresh image v0.3.9
       Fresh glutin v0.1.3
       Fresh glium v0.3.7
       Fresh calx v0.0.1 (https://github.com/rsaarelm/calx#1f6ce2a8)
       Fresh world v0.0.1 (file:///Users/jared/Code/phage)
       Fresh phage v0.1.0 (file:///Users/jared/Code/phage)
     Running `target/debug/phage`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: CompilationError("ERROR: 0:1: \'\' :  version \'120\' is not supported\nERROR: 0:2: \'\' :  #version required and missing.\nERROR: 0:3: \'attribute\' : syntax error: syntax error\n")', /Users/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-mac/build/src/libcore/result.rs:729
Process didn't exit successfully: `target/debug/phage` (exit code: 101)
```

**Comment by rsaarelm** [comment]
The error is from the OpenGL module (glium or whatever is below it) not being able to run the shader code. I don't have OS X and I don't really know anything about how graphics drivers on it work, so I can't troubleshoot this myself. Is it possible that you have very old OpenGL drivers?

If you want to look into this, start out by downloading [glium](https://github.com/tomaka/glium) and doing `cargo run --example triangle`. If you get a triangle showing up, then it might be a problem at my end.

**Comment by dobrite** [comment]
I too hit this error on OSX. FWIW the glium triangle example works. Both were just now cloned and ran on Rust release 1.0.0.

**Comment by rsaarelm** [comment]
I changed the shader GLSL version from 120 to 140. Can you try again with the latest master commit?

**Comment by rsaarelm** [comment]
I can't test this myself, so I'm closing this for now since the reversioned shaders should be more OS X friendly. Reopen if there's still problems.
